use crate::algorithm::{AlgorithmConfig, AlgorithmType};
use crate::config::rule::{Rule, RuleType};
use crate::key_extractor::KeyExtractor;
use serde::{Deserialize, Serialize};
use std::time::Duration;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuleTemplate {
    pub id: String,
    pub name: String,
    pub description: String,
    pub category: String,
    pub rule: Rule,
}

pub fn builtin_templates() -> Vec<RuleTemplate> {
    vec![
        RuleTemplate {
            id: "ip-rate-limit".to_string(),
            name: "按 IP 限流".to_string(),
            description: "基于客户端 IP 地址进行限流，适用于防刷、防爬虫场景".to_string(),
            category: "基础".to_string(),
            rule: Rule {
                id: "".to_string(),
                name: Some("IP 限流".to_string()),
                description: Some("按客户端 IP 限流".to_string()),
                rule_type: RuleType::Global,
                enabled: true,
                priority: 100,
                algorithm: AlgorithmConfig::token_bucket(100, 200, None),
                key_extractor: KeyExtractor::ip(),
                path_prefix: None,
                ip_list: None,
                graylist_multiplier: None,
                group: None,
                start_at: None,
                end_at: None,
                stats: Default::default(),
            },
        },
        RuleTemplate {
            id: "user-rate-limit".to_string(),
            name: "按用户限流".to_string(),
            description: "基于用户 ID 进行限流，需要从 header 的 X-User-Id 提取".to_string(),
            category: "基础".to_string(),
            rule: Rule {
                id: "".to_string(),
                name: Some("用户限流".to_string()),
                description: Some("按用户 ID 限流".to_string()),
                rule_type: RuleType::Global,
                enabled: true,
                priority: 100,
                algorithm: AlgorithmConfig::token_bucket(50, 100, None),
                key_extractor: KeyExtractor::header("X-User-Id"),
                path_prefix: None,
                ip_list: None,
                graylist_multiplier: None,
                group: None,
                start_at: None,
                end_at: None,
                stats: Default::default(),
            },
        },
        RuleTemplate {
            id: "global-rate-limit".to_string(),
            name: "全局限流".to_string(),
            description: "全局统一限流，保护整体服务容量".to_string(),
            category: "基础".to_string(),
            rule: Rule {
                id: "".to_string(),
                name: Some("全局限流".to_string()),
                description: Some("全局统一限流".to_string()),
                rule_type: RuleType::Global,
                enabled: true,
                priority: 1,
                algorithm: AlgorithmConfig::fixed_window(10000, Duration::from_secs(1)),
                key_extractor: KeyExtractor::global(),
                path_prefix: None,
                ip_list: None,
                graylist_multiplier: None,
                group: None,
                start_at: None,
                end_at: None,
                stats: Default::default(),
            },
        },
        RuleTemplate {
            id: "api-path-rate-limit".to_string(),
            name: "按 API 路径限流".to_string(),
            description: "基于 API 路径前缀进行细分限流".to_string(),
            category: "基础".to_string(),
            rule: Rule {
                id: "".to_string(),
                name: Some("API 路径限流".to_string()),
                description: Some("按 API 路径前缀限流".to_string()),
                rule_type: RuleType::PathPrefix,
                enabled: true,
                priority: 50,
                algorithm: AlgorithmConfig::sliding_window(1000, Duration::from_secs(60)),
                key_extractor: KeyExtractor::ip(),
                path_prefix: Some("/api/".to_string()),
                ip_list: None,
                graylist_multiplier: None,
                group: None,
                start_at: None,
                end_at: None,
                stats: Default::default(),
            },
        },
        RuleTemplate {
            id: "ip-blacklist".to_string(),
            name: "IP 黑名单".to_string(),
            description: "直接拒绝黑名单 IP 的所有请求".to_string(),
            category: "安全".to_string(),
            rule: Rule {
                id: "".to_string(),
                name: Some("IP 黑名单".to_string()),
                description: Some("直接拒绝黑名单 IP".to_string()),
                rule_type: RuleType::IpBlacklist,
                enabled: true,
                priority: 200,
                algorithm: AlgorithmConfig::fixed_window(0, Duration::from_secs(1)),
                key_extractor: KeyExtractor::ip(),
                path_prefix: None,
                ip_list: Some(vec![]),
                graylist_multiplier: None,
                group: None,
                start_at: None,
                end_at: None,
                stats: Default::default(),
            },
        },
        RuleTemplate {
            id: "ip-whitelist".to_string(),
            name: "IP 白名单".to_string(),
            description: "白名单 IP 直接放行，跳过所有限流检查".to_string(),
            category: "安全".to_string(),
            rule: Rule {
                id: "".to_string(),
                name: Some("IP 白名单".to_string()),
                description: Some("白名单 IP 放行".to_string()),
                rule_type: RuleType::IpWhitelist,
                enabled: true,
                priority: 200,
                algorithm: AlgorithmConfig::fixed_window(u64::MAX, Duration::from_secs(1)),
                key_extractor: KeyExtractor::ip(),
                path_prefix: None,
                ip_list: Some(vec![]),
                graylist_multiplier: None,
                group: None,
                start_at: None,
                end_at: None,
                stats: Default::default(),
            },
        },
        RuleTemplate {
            id: "promotion-event".to_string(),
            name: "活动期限流".to_string(),
            description: "带有效期的活动限流，如双11大促".to_string(),
            category: "活动".to_string(),
            rule: Rule {
                id: "".to_string(),
                name: Some("活动期限流".to_string()),
                description: Some("活动期间专用限流规则".to_string()),
                rule_type: RuleType::Global,
                enabled: true,
                priority: 10,
                algorithm: AlgorithmConfig::token_bucket(500, 1000, Some(Duration::from_secs(30))),
                key_extractor: KeyExtractor::ip(),
                path_prefix: None,
                ip_list: None,
                graylist_multiplier: None,
                group: None,
                start_at: None,
                end_at: None,
                stats: Default::default(),
            },
        },
    ]
}

pub fn default_test_rules() -> Vec<Rule> {
    vec![Rule {
        id: "test-global".to_string(),
        name: Some("测试全局限流".to_string()),
        description: Some("默认测试规则".to_string()),
        rule_type: RuleType::Global,
        enabled: true,
        priority: 1,
        algorithm: AlgorithmConfig::fixed_window(10, Duration::from_secs(60)),
        key_extractor: KeyExtractor::ip(),
        path_prefix: None,
        ip_list: None,
        graylist_multiplier: None,
        group: None,
        start_at: None,
        end_at: None,
        stats: Default::default(),
    }]
}

pub fn algorithm_type_to_string(algo: AlgorithmType) -> &'static str {
    match algo {
        AlgorithmType::FixedWindow => "fixed_window",
        AlgorithmType::SlidingWindow => "sliding_window",
        AlgorithmType::TokenBucket => "token_bucket",
    }
}
